"""Add circuit_id to Customer

Revision ID: 26a8dcde2b5c
Revises: 217329c4f338
Create Date: 2025-06-27 13:53:37.814361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a8dcde2b5c'
down_revision = '217329c4f338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circuit_id', sa.String(length=100), nullable=True))
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('contact_person')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_person', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('circuit_id')

    # ### end Alembic commands ###
