"""Add owner_of_ticket and assigned_to_person to Fault

Revision ID: be0a9168b8e8
Revises: 26a8dcde2b5c
Create Date: 2025-06-30 10:47:37.270098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0a9168b8e8'
down_revision = '26a8dcde2b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fault', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_of_ticket', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_person', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fault', schema=None) as batch_op:
        batch_op.drop_column('assigned_to_person')
        batch_op.drop_column('owner_of_ticket')

    # ### end Alembic commands ###
