"""Add closed_at to Fault

Revision ID: c5f6692658e1
Revises: be0a9168b8e8
Create Date: 2025-06-30 11:46:19.304345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f6692658e1'
down_revision = 'be0a9168b8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fault', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fault', schema=None) as batch_op:
        batch_op.drop_column('closed_at')

    # ### end Alembic commands ###
